# Generated by Django 3.0.5 on 2020-11-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_nickname', models.CharField(max_length=25, unique=True)),
                ('user_name', models.CharField(max_length=25)),
                ('user_last_name', models.CharField(max_length=25)),
                ('user_role', models.IntegerField()),
                ('user_image', models.ImageField(upload_to=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthday', models.DateTimeField()),
                ('address', models.CharField(max_length=50)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.CharField(blank=True, max_length=50, null=True)),
                ('hours_worked', models.IntegerField(blank=True, null=True)),
                ('salary_per_hour', models.IntegerField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
