# Generated by Django 3.0.5 on 2020-11-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20201123_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
