# Generated by Django 3.0.5 on 2020-11-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_account_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='has_module_perms',
        ),
    ]
