# Generated by Django 3.0.5 on 2020-11-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_account_has_module_perms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_name',
            new_name='user_first_name',
        ),
    ]
