# Generated by Django 3.0.5 on 2020-11-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20201123_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_nickname',
            new_name='user_name',
        ),
    ]
