# Generated by Django 3.0.5 on 2020-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id_cycle', models.IntegerField(primary_key=True, serialize=False)),
                ('cycle_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id_phase', models.IntegerField(primary_key=True, serialize=False)),
                ('phase_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_priority', models.IntegerField()),
                ('priority_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.IntegerField()),
                ('project_name', models.CharField(max_length=50)),
                ('creator_name', models.CharField(max_length=50)),
                ('lider', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('phase', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.IntegerField()),
                ('id_task', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id_system', models.IntegerField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.IntegerField()),
                ('task_name', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('creator_name', models.CharField(max_length=50)),
                ('date_of_creation', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('is_open', models.BooleanField()),
                ('close_day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.IntegerField()),
                ('id_user_name', models.IntegerField()),
                ('is_in_progress', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_team', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=15)),
            ],
        ),
    ]
